version: "3.3"
services:
  music-library-api-2-db:
    container_name: music-library-api-2-mysql-db
    image: mysql:5.7
    restart: always
    command: --sql_mode="NO_ENGINE_SUBSTITUTION"
    environment:
      MYSQL_DATABASE: "music_library_api_2_db"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - vol-music-library-api-2-db:/var/lib/mysql
volumes:
  vol-music-library-api-2-db:
